### PR TITLE
Dev-service decorators that provide hook(s) for generated/dynamic css post processing

### PR DESCRIPTION
**Pull request by stefanospetrakis**

### CODE REVIEW

**Comment by stefanospetrakis** [comment]
* Decorating the services that would allow string manipulating pagedesigner and other css that uses relative paths in background-image: url() and wouldn't allow asset proxying via stage file proxy
* This is dev only code, iq_stage_file_proxy is require-dev
* This will allow fixing those VRT tests that fail due to missing assets
* It will also allow a much better DX, since local dev environments should be delivering all assets when using this code.
* Introducing this change completely "greened-out" or reduced the number of reported failures (see stats below)
* Also, the mismatch threshold was reduced to 5% from 2000% https://github.com/iqual-ch/php-backstop-generator/commit/50552f81720aa802633cd9d8897ada5ff4ef43c2 (becoming much more sensitive to vis.reg.)
* With this code change and the threshold change, we should be getting (really really) true negatives, which wasn't the case so far.

Some stats re. failing VRT tests (before => after; pass/fail):
+ engelcopera-sw-project:  31/19 => 49/1
+ aarebier-sw-project:  13/35 => 47/1
+ knechtgarten-sw-project: 5/45 => 29/21
+ urs-amsler-sw-project: 50/0 => 50/0 (no change)
+ tilia-sw-project: 50/0 => 50/0 (no change)

**Comment by pvbergen** [comment]
Is the decoration a soft or hard dependency? If soft, we can merge. If hard, we move the decoraters into a submodule.

**Comment by stefanospetrakis** [comment]
So, this would fail with a:

image

Since SF 4.4 there is a `decoration_on_invalid: ignore` setting in services.yml; however, it doesn't work for Drupal it seems. Therefore, using a container alter() method in this PR.

**Review by pvbergen — APPROVED** [review]
Assuming it's a soft dependency using the alter method.

**Review by martinstadelmann — APPROVED** [review]

**Pull request merged**
